In [25]:
import numpy as np
import math

In [29]:
# First, regular points in 2D

# Translation is a vector
translation1 = np.array([2,1], np.float)
translation2 = np.array([-5,6], np.float)
# Rotation is a 2x2 matrix
rotation = np.array([[math.cos(math.pi/2), -math.sin(math.pi/2)], [math.sin(math.pi/2), math.cos(math.pi/2)]], np.float)
# Scaling is a 2x2 matrix
scaling = np.array([[3,0], [0, 2]], np.float)

print('translation1 =', translation1)
print('translation2 =', translation1)
print('rotation\n', rotation)
print('scaling\n', scaling)

point = np.array([5,2], np.float)

# Apply the sequence of transformations
# First translate, then scale, then rotate, then translate again
new_point = translation2 + rotation.dot(scaling.dot(point + translation1))

print('')
print('transformed point = ', new_point)

translation1 = [2. 1.]
translation2 = [2. 1.]
rotation
 [[ 6.123234e-17 -1.000000e+00]
 [ 1.000000e+00  6.123234e-17]]
scaling
 [[3. 0.]
 [0. 2.]]

transformed point =  [-11.  27.]


In [33]:
# Now, as homeogeneous coordinates in 3D (x,y,1)

# Translation is a 3x3 matrix
translation1 = np.array([[1, 0, 2], [0, 1, 1], [0, 0, 1]], np.float)
translation2 = np.array([[1, 0, -5], [0, 1, 6], [0, 0, 1]], np.float)
# Rotation is a 3x3 matrix
rotation = np.array([[math.cos(math.pi/2), -math.sin(math.pi/2), 0], [math.sin(math.pi/2), math.cos(math.pi/2), 0], [0,0,1]], np.float)
# Scaling is a 3x3 matrix
scaling = np.array([[3,0,0], [0, 2,0], [0,0,1]], np.float)

print('translation1\n', translation1)
print('translation2\n', translation2)
print('rotation\n', rotation)
print('scaling\n', scaling)

point = np.array([5,2,1], np.float)

# Apply the sequence of transformations
new_point = translation2.dot(rotation.dot(scaling.dot(translation1.dot(point))))

print('')
print('new point = ', new_point)

# Combine the sequence of transformations into a single transformation by matrix multiplication
combined = translation2.dot(rotation.dot(scaling.dot(translation1)))

# Show the combined affinie matrix
print('')
print('Affine transform\n', combined)

# Apply the combined matrix to the point to see the result is the same
new_point2 = combined.dot(point)

print('')
print('new point2 = ', new_point2)

translation1
 [[1. 0. 2.]
 [0. 1. 1.]
 [0. 0. 1.]]
translation2
 [[ 1.  0. -5.]
 [ 0.  1.  6.]
 [ 0.  0.  1.]]
rotation
 [[ 6.123234e-17 -1.000000e+00  0.000000e+00]
 [ 1.000000e+00  6.123234e-17  0.000000e+00]
 [ 0.000000e+00  0.000000e+00  1.000000e+00]]
scaling
 [[3. 0. 0.]
 [0. 2. 0.]
 [0. 0. 1.]]

new point =  [-11.  27.   1.]

Affine transform
 [[ 1.8369702e-16 -2.0000000e+00 -7.0000000e+00]
 [ 3.0000000e+00  1.2246468e-16  1.2000000e+01]
 [ 0.0000000e+00  0.0000000e+00  1.0000000e+00]]

new point2 =  [-11.  27.   1.]
